name: satria
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: 2.5.3

dependencies: 
  cupertino_icons: ^1.0.2
  fluttertoast: 8.0.8
  google_fonts: 2.1.0
  shimmer: 2.0.0
  flutter_easyloading: 3.0.3
  flutter_bloc: 7.3.2
  freezed_annotation: 0.15.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  json_annotation: 4.3.0
  flutter_secure_storage: 4.2.1
  wc_form_validators: 1.0.0
  flutter_font_icons: 2.2.4
  lottie: 1.2.1
  random_password_generator: 0.2.1
  local_auth: 1.1.8
  url_launcher: 6.0.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  json_serializable: 6.0.1
  freezed: 0.15.0+1
  hive_generator: 1.1.1
  build_runner: 2.1.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/lottie/
  uses-material-design: true

