///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const imageHomelogo = 'assets/image/homelogo.png';
  static const logoPathNational = 'assets/kisslogologin.png';
  static const logoPathInternational = 'assets/kisslogo.png';
  static const googleImage = 'assets/google.jpg';
  static const appleImage = 'assets/apple.png';
}
